- name: Disable existing {{ packageName }} module stream for {{ component }} server
  ansible.builtin.shell: dnf module disable {{ packageName }} -y

- name: Enable {{ packageName }} module stream {{ packageVersion }}
  ansible.builtin.shell: dnf module enable {{ packageName }}:{{ packageVersion }} -y

- name: Installing "{{ packageName }}" 
  ansible.builtin.package:
    name: "{{ packageName }}" 
    state: present

- name: creating appuser for {{ component }} service
  ansible.builtin.user:
    name: "{{ appUser }}"
    create_home: yes

- name: Cleanup of the {{ appDirectory }} content
  ansible.builtin.file:
    path: "{{ appDirectory }}"
    state: absent

- name: Creating app directory for {{ component }} service
  ansible.builtin.file:
    path: "{{ appDirectory }}"
    state: directory

- name: Download and extracting the {{ component }} service
  ansible.builtin.unarchive:
    src: "{{ url }}"
    dest: "{{ appDirectory }}"
    remote_src: yes           # If yes, download from the URL mentioned in src machine, if no, copy from local machine to remote machine

- name: Generating artifact dependencies for {{ component }} service
  community.general.npm:
    path: "{{ appDirectory }}" 

- name: Configuring the {{ component }} service
  ansible.builtin.template:
    src: "{{ component }}.service"
    dest: "/etc/systemd/system/{{ component }}.service"

- name: Configuring the mongodb repo 
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing mongodbShell
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: present

- name: Injecting Mongodb Schema for {{ component }} service
  ansible.builtin.shell: "mongosh --host mongodb-{{ env }}.robotshop.fun < /app/db/master-data.js"  

- name: Starting {{ component }} service
  ansible.builtin.service:
    name: "{{ component }}"
    enabled: yes
    state: restarted
    daemon_reload: yes

- name: Configuring the hostName
  ansible.builtin.shell: set-hostname {{ component }}-{{ env }}