- name: demo on variables
  hosts: all
  become: true  
  vars:
    name: "ansible"
    version: "2.14"
    URL: "https://www.ansible.com/"
  tasks:
    - name: print the variables
      debug:
        msg: "The name is {{ name }}, the version is {{ version }}, and the URL is {{ URL }}"

  
- name: print the global variable
  hosts: all
  become: true
  vars:
    version: "ansible version"
  tasks:
    - name: print the global variable
      ansible.builtin.shell: "ansible --version"
      register: version_output
      ignore_errors: true
    - name: print the version output
      debug:
        msg: "The version is {{ version_output.stdout }}"
      ignore_errors: true
