- name: diable default nginx version
  ansible.builtin.dnf:
    name: nginx
    state: absent
- name: enable nginx 1.24 version
  ansible.builtin.dnf:
    name: nginx
    state: present
    version: 1.24
- name: copy nginx configuration file
  ansible.builtin.package:
    name: nginx
    state: present
- name: start nginx service
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
- name: configure hostname
  ansible.builtin.shell: set-hostname frontend.{{env}}
