- name: diable default nginx version
  ansible.builtin.shell: dnf module disable nginx -y

- name: enable nginx 1.24 version
  ansible.builtin.shell: dnf module install nginx:1.24 -y

- name: install the nginx
  ansible.builtin.package:
    name: nginx
    state: present 
- name: configure hostname
  ansible.builtin.shell: set-hostname frontend.{{ env }}